import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { ApolloClient, ApolloProvider, InMemoryCache } from '@apollo/client';
import { ClientOnly } from '../components/ClientOnly';
import React from 'react';
import Head from 'next/head';

const client = new ApolloClient({
  uri: '/api/graphql',
  cache: new InMemoryCache(),
});

function MyApp({ Component, pageProps }: AppProps): React.ReactNode {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClientOnly>
        <ApolloProvider client={client}>
          <Component {...pageProps} />
        </ApolloProvider>
      </ClientOnly>
    </div>
  );
}

export default MyApp;
